name: GreifControl
version: 0.7
description: Prevent Greifing with certain blocks.
author: JamieSinn
website: http://dev.bukkit.org/server-mods/greifcontrol/ 
main: me.JamieSinn.Bukkit.GreifControl
database: false


commands:




permissions:
  GreifControl.override:
    description: Gives access to place restricted blocks.

 

